language: node_js
node_js:
- 4.2
notifications:
  slack:
    secure: u4t9vP7X7W7NXonT31T1j2lFNWH3gK+XP9W7qUVP60Hh6/L+9edtl2rrloJiW320RWiGbSWDhmdkIh1drsawtNPQgZhWE+Wh9nsejFuNfJK3c+gim1HTC3oHiOAlRIP0VciegGshTSS9yzOaLqAxr6nwr8DYJxxPtiluIz3ov/79TTHTCUNrz1UPnSrN1FAg4uWEZCAIQ1dseW2FqWw8XF8mwvklOmWJ2oj69mNjpZzUlY5H07Uko7bh0RoYisL0BlG/NRF3WQxixGrfFMTpMSYj1cxviubaNpQm4QlstRxQQM4Zf/Bm3RDmHTmpG4obH5TWNxF4ckZrkMhI7NFqdkc54n6rLo+9P1zQCNWnqCWLL4V9JwNz8BjMIcP37WlzcOclmy1EEeJwkdDUxq9zZM27nzvr1qehpmCmNb6BxnyuhOH5UMUdz2G+3LLZDP+BNfVOd+y0gLqVkj0WnsToOBRSR7I5RBZjby2Vkgg5tbxD1bZR/JYp/hwoSFVq48PmSZJJVH1IfSkPL5AUC5YJ0A3sThXy/EQ8l1OTK9EPFKbktzwDqgZTTMaGn394qXBYaX2RlEfj2r/IBIQ/O1paM8sV94++NH8YiPVOlKKE+9tEhwOpr7Uc85n8wlOGVjupKX94BJaJ2xD2qz6+qgK1zQiMF73WlKSU41S8iH4LaJU=
